import { RecipeRegister } from "./register/RecipeRegister";
import { Food } from "./register/Food";
import { LootingRegister } from "./register/LootingRegister";
import { BlockFood } from "./register/BlockFood";
import { FishingNet } from "./register/FishingNet";
import { WildSeaGrapeRegister } from "./crop/WildSeaGrapeRegister";
import { SeaGrapePlantRegister } from "./crop/SeaGrapePlantRegister";
import { SeaGrapePlantBottomRegister } from "./crop/SeaGrapePlantBottomRegister";
import { SeaGrapeRegister } from "./crop/SeaGrapeRegister";
import { Book } from "./register/Book";
new Book();
new SeaGrapeRegister();
new SeaGrapePlantBottomRegister();
new SeaGrapePlantRegister();
new WildSeaGrapeRegister();
new FishingNet();
new BlockFood();
new LootingRegister();
new Food();
new RecipeRegister();